// <auto-generated />
namespace SpacesForChildren.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class displaynameadddedoncontract : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(displaynameadddedoncontract));
        
        string IMigrationMetadata.Id
        {
            get { return "201801070102055_display-name-addded-on-contract"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
